spring.application.name=Enotes_API_Service

spring.datasource.url=jdbc:mysql://localhost:3306/enotes_dev
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Merc@123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
## Enable general debug mode
#debug=true
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG

file.upload.path =paths/


#Email send config
spring.mail.host=smtp.gmail.com
spring.mail.username=suraj.xangarslabs@gmail.com
spring.mail.password=evpe vtgt xfep hfys
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

